
name: .NET Core Desktop

on:
  push:
    branches:
    - "master"
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Settup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 10.0.x
    - name: Restore Dependencies
      run: dotnet restore BrainBuster
    - name: Build
      run: dotnet build BrainBuster --no-restore
    - name: Test
      run: dotnet test BrainBuster --no-build --verbosity normal
    #- name: Deploy
    #  run: dotnet run BrainBuster

