
name: .NET Core Desktop

on:
  push:
    branches:
    - 'release/**'

jobs:

  build-and-test:

    runs-on: ubuntu-latest
                           

    steps:
    - uses: actions/checkout@v4
    - name: Settup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore Dependencies
      run: dotnet restore ./BrainBuster.csproj
    - name: Build
      run:  dotnet build ./BrainBuster.csproj --no-restore
    - name: Test
      run: dotnet test ./Tests/BrainBuster.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"
    

